# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='_User',
            fields=[
                ('objectId', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('salt', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sessionToken', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30)),
                ('emailVerified', models.BooleanField()),
                ('mobilePhoneNumber', models.CharField(max_length=30)),
                ('authData', models.CharField(max_length=100)),
                ('userRole', models.CharField(max_length=20)),
                ('mobilePhoneVerified', models.BooleanField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('objectId', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u4e3b\u952eid')),
                ('limit', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('begin', models.DateTimeField()),
                ('idDelete', models.CharField(max_length=10)),
                ('isShow', models.CharField(max_length=10)),
                ('joinnum', models.IntegerField()),
                ('end', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ActJoinLog',
            fields=[
                ('objectId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('extra', models.IntegerField()),
                ('star', models.IntegerField()),
                ('isInner', models.BooleanField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='ActRegistration',
            fields=[
                ('objectId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('isInner', models.BooleanField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('objectId', models.CharField(max_length=30, unique=True, verbose_name='id')),
                ('address', models.CharField(max_length=300, verbose_name='\u5730\u5740')),
                ('person', models.CharField(max_length=30, verbose_name='\u7ba1\u7406\u5458')),
                ('pwd', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('name', models.CharField(max_length=200, verbose_name='\u5355\u4f4d\u7ec4\u7ec7\u540d\u79f0')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('type', models.CharField(max_length=30, verbose_name='\u7c7b\u522b\uff0c\u5355\u4f4dor\u793e\u533a')),
                ('tel', models.CharField(max_length=30, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u4e3b\u952eid')),
                ('isShow', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=30)),
                ('flagNumber', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('objectId', models.CharField(max_length=30, unique=True, verbose_name='\u4e3b\u952eid')),
                ('address', models.CharField(max_length=300, verbose_name='\u5730\u5740')),
                ('realname', models.CharField(max_length=50, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('sex', models.CharField(max_length=10, verbose_name='\u6027\u522b')),
                ('idcard', models.CharField(max_length=30, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('checkin', models.CharField(max_length=300, verbose_name='bool,\u7b7e\u5230\u65e5\u671f\u7528\uff0c\u9694\u5f00')),
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('political', models.CharField(max_length=50, verbose_name='\u515a\u7ec4\u7ec7\u8eab\u4efd')),
                ('isShow', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=30, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('flagNumber', models.CharField(max_length=20, verbose_name='')),
                ('brith', models.DateField(verbose_name='\u751f\u65e5\uff0c\u5e74\u6708\u65e5')),
                ('job', models.CharField(max_length=300, verbose_name='\u804c\u4e1a')),
                ('createdAt', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatedAt', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='app1.Admins')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='app1.Admins')),
            ],
        ),
        migrations.AddField(
            model_name='actregistration',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actR_admin_group', to='app1.Admins'),
        ),
        migrations.AddField(
            model_name='actregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Users'),
        ),
        migrations.AddField(
            model_name='actregistration',
            name='userGroupArr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actR_user_location', to='app1.Admins'),
        ),
        migrations.AddField(
            model_name='actregistration',
            name='userLocationArr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actR_user_group', to='app1.Admins'),
        ),
        migrations.AddField(
            model_name='actjoinlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actJL_admin_group', to='app1.Admins'),
        ),
        migrations.AddField(
            model_name='actjoinlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Users'),
        ),
        migrations.AddField(
            model_name='actjoinlog',
            name='userGroupArr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actJL_user_group', to='app1.Admins'),
        ),
        migrations.AddField(
            model_name='actjoinlog',
            name='userLocationArr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actJL_user_location', to='app1.Admins'),
        ),
        migrations.AddField(
            model_name='activities',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Admins'),
        ),
    ]
