# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='brith',
            field=models.DateField(null=True, verbose_name='\u751f\u65e5\uff0c\u5e74\u6708\u65e5'),
        ),
    ]
