# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170211_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_user',
            name='authData',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='_user',
            name='mobilePhoneNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='mobilePhoneVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='_user',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='salt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='sessionToken',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='userRole',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='idDelete',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='isShow',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='joinnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='limit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='place',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Activities'),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actJL_admin_group', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='extra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='isInner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='star',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Users'),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='userGroupArr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actJL_user_group', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='actjoinlog',
            name='userLocationArr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actJL_user_location', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Activities'),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actR_admin_group', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='isInner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Users'),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='userGroupArr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actR_user_location', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='userLocationArr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actR_user_group', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='flagNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='isShow',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='\u5355\u4f4d\u7ec4\u7ec7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='person',
            field=models.CharField(max_length=30, null=True, verbose_name='\u7ba1\u7406\u5458'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='pwd',
            field=models.CharField(max_length=20, null=True, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='tel',
            field=models.CharField(max_length=30, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='type',
            field=models.CharField(max_length=30, null=True, verbose_name='\u7c7b\u522b\uff0c\u5355\u4f4dor\u793e\u533a'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='users',
            name='checkin',
            field=models.CharField(max_length=300, null=True, verbose_name='bool,\u7b7e\u5230\u65e5\u671f\u7528\uff0c\u9694\u5f00'),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='users',
            name='flagNumber',
            field=models.CharField(max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='users',
            name='idcard',
            field=models.CharField(max_length=30, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AlterField(
            model_name='users',
            name='isShow',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.CharField(max_length=300, null=True, verbose_name='\u804c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='app1.Admins'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(max_length=30, null=True, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='users',
            name='political',
            field=models.CharField(max_length=50, null=True, verbose_name='\u515a\u7ec4\u7ec7\u8eab\u4efd'),
        ),
        migrations.AlterField(
            model_name='users',
            name='realname',
            field=models.CharField(max_length=50, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(max_length=10, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
