# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20170211_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='brith',
        ),
        migrations.AddField(
            model_name='users',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='\u751f\u65e5\uff0c\u5e74\u6708\u65e5'),
        ),
    ]
