# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20170211_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='idDelete',
            new_name='isDelete',
        ),
    ]
