# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170211_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actregistration',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actR_user_group', to='app1.Activities'),
        ),
        migrations.AlterField(
            model_name='actregistration',
            name='isInner',
            field=models.NullBooleanField(default=False),
        ),
    ]
