# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20170219_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_user',
            name='authData',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='_user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='_user',
            name='mobilePhoneNumber',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='_user',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='_user',
            name='salt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='_user',
            name='sessionToken',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='_user',
            name='userRole',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='_user',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admins',
            name='address',
            field=models.CharField(default='', max_length=300, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='flagNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='admins',
            name='isShow',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='admins',
            name='mobile',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admins',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='\u5355\u4f4d\u7ec4\u7ec7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='person',
            field=models.CharField(default='', max_length=30, verbose_name='\u7ba1\u7406\u5458'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='pwd',
            field=models.CharField(default='', max_length=20, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='tel',
            field=models.CharField(default='', max_length=30, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='type',
            field=models.CharField(default='', max_length=30, verbose_name='\u7c7b\u522b\uff0c\u5355\u4f4dor\u793e\u533a'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
