# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20170301_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(default='', max_length=300, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='users',
            name='flagNumber',
            field=models.CharField(default='', max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='idcard',
            field=models.CharField(default='', max_length=30, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AlterField(
            model_name='users',
            name='isShow',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.CharField(default='', max_length=300, verbose_name='\u804c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(default='', max_length=30, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='users',
            name='political',
            field=models.CharField(default='', max_length=50, verbose_name='\u515a\u7ec4\u7ec7\u8eab\u4efd'),
        ),
        migrations.AlterField(
            model_name='users',
            name='realname',
            field=models.CharField(default='', max_length=50, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
