# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20170301_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_user',
            name='authData',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='mobilePhoneNumber',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='password',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='salt',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='sessionToken',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='userRole',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='_user',
            name='username',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
