# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20170302_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity2Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_id', models.CharField(max_length=30)),
                ('tag_id', models.IntegerField()),
                ('createdAt', models.DateTimeField(null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=300, null=True)),
                ('createdAt', models.DateTimeField(null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
    ]
