# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20170313_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='isDelete',
            field=models.IntegerField(default=0),
        ),
    ]
