# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_tag_isdelete'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='admins',
#            name='flagNumber',
#        ),
    ]
