# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20170319_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='isDelete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='isDelete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='flagNumber',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='flagNumber'),
        ),
    ]
